# Generated by Django 2.1.15 on 2021-12-21 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('post', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField(auto_now=True)),
                ('morning', models.BooleanField(default=False)),
                ('afternoon', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('occupation', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('dob', models.DateTimeField(default=django.utils.timezone.now)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('post_box', models.IntegerField()),
                ('town', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField()),
                ('Occupation', models.CharField(max_length=100)),
                ('extra_role', models.CharField(default='None', max_length=100, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('grade', models.IntegerField(choices=[(-3, 'Playgroup'), (-2, 'PP1'), (-1, 'PP2'), (1, 'G1'), (2, 'G2'), (3, 'G3'), (4, 'G4'), (5, 'G5'), (6, 'G6'), (7, 'General Teacher'), (8, 'Support Staff'), (9, 'Administrative Staff')])),
                ('salary', models.IntegerField()),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('certified', models.BooleanField(default='No')),
                ('dob', models.DateField(blank=True, null=True)),
                ('day_recruited', models.DateField(blank=True, null=True)),
                ('day_retirement', models.DateField(blank=True, null=True)),
                ('next_of_kin', models.CharField(max_length=100)),
                ('kin_contact', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('photo', models.ImageField(default='john.png', upload_to='profile_photos')),
                ('transfered', models.BooleanField(default=False, verbose_name='Transfered?')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100, null=True)),
                ('extra_role', models.CharField(default='None', max_length=100, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='female', max_length=20)),
                ('dob', models.DateField(blank=True, null=True)),
                ('grade', models.IntegerField(choices=[(-3, 'Playgroup'), (-2, 'PP1'), (-1, 'PP2'), (1, 'G1'), (2, 'G2'), (3, 'G3'), (4, 'G4'), (5, 'G5'), (6, 'G6'), (7, 'General Teacher'), (8, 'Support Staff'), (9, 'Administrative Staff')])),
                ('parent_phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('transfered', models.BooleanField(default=False, verbose_name='Transfered?')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Student'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Staff'),
        ),
    ]
