# Generated by Django 3.2.4 on 2021-10-19 09:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('occupation', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('dob', models.DateTimeField(default=django.utils.timezone.now)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('grade', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('certified', models.BooleanField(default='No')),
                ('id_number', models.IntegerField()),
                ('dob', models.DateField(blank=True, null=True)),
                ('next_of_kin', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('day_recruited', models.DateTimeField(auto_now=True)),
                ('day_retirement', models.DateTimeField()),
                ('kin_contact', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('photo', models.ImageField(default='charles.png', upload_to='profile_photos')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(max_length=20)),
                ('dob', models.DateField(blank=True, null=True)),
                ('grade', models.CharField(max_length=100)),
                ('parent_phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField(auto_now=True)),
                ('morning', models.BooleanField(default=False)),
                ('afternoon', models.BooleanField(default=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.student')),
            ],
        ),
    ]
