# Generated by Django 3.2.4 on 2021-10-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=20),
        ),
        migrations.AlterField(
            model_name='staff',
            name='grade',
            field=models.CharField(choices=[('Playgroup', 'Playgroup'), ('PP1', 'PP1'), ('PP2', 'PP2'), ('G1', 'G1'), ('G2', 'G2'), ('G3', 'G2'), ('G4', 'G2'), ('G5', 'G2'), ('G6', 'G2'), ('general', 'General')], max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('Playgroup', 'Playgroup'), ('PP1', 'PP1'), ('PP2', 'PP2'), ('G1', 'G1'), ('G2', 'G2'), ('G3', 'G2'), ('G4', 'G2'), ('G5', 'G2'), ('G6', 'G2'), ('general', 'General')], max_length=100),
        ),
    ]
