# Generated by Django 3.2.4 on 2021-10-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20211023_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='extra_role',
            field=models.CharField(default='None', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='extra_role',
            field=models.CharField(default='None', max_length=100, null=True),
        ),
    ]
