# Generated by Django 3.2.4 on 2021-10-23 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20211023_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='role',
            new_name='Occupation',
        ),
    ]
