# Generated by Django 3.2.4 on 2021-10-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_rename_role_staff_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='day_recruited',
            field=models.DateTimeField(),
        ),
    ]
