# Generated by Django 3.2.4 on 2021-11-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20211124_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='grade',
            field=models.CharField(choices=[('Playgroup', 'Playgroup'), ('PP1', 11), ('PP2', 12), ('G1', 1), ('G2', 2), ('G3', 3), ('G4', 4), ('G5', 5), ('G6', 6), ('General_teacher', 'General Teacher'), ('support_staff', 'Support Staff'), ('admin_staff', 'Administrative Staff')], max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('Playgroup', 'Playgroup'), ('PP1', 11), ('PP2', 12), ('G1', 1), ('G2', 2), ('G3', 3), ('G4', 4), ('G5', 5), ('G6', 6), ('General_teacher', 'General Teacher'), ('support_staff', 'Support Staff'), ('admin_staff', 'Administrative Staff')], max_length=100),
        ),
    ]
