# Generated by Django 3.2.4 on 2021-10-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_remove_staff_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='photo',
            field=models.ImageField(default=1, upload_to='profile_photos'),
            preserve_default=False,
        ),
    ]
