# Generated by Django 3.2.4 on 2021-10-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_student_admission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='photo',
            field=models.ImageField(default='images.png', upload_to='profile_photos'),
        ),
    ]
