# Generated by Django 3.2.4 on 2021-10-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_staff_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='day_recruited',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='day_retirement',
            field=models.DateField(blank=True, null=True),
        ),
    ]
