# Generated by Django 3.2.4 on 2021-10-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20211029_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='grade',
            field=models.CharField(choices=[('Playgroup', 'Playgroup'), (-2, 'PP1'), (-1, 'PP2'), (1, 'G1'), (2, 'G2'), ('3', 'G3'), ('4', 'G4'), ('5', 'G5'), ('6', 'G6'), ('General_teacher', 'General Teacher'), ('support_staff', 'Support Staff'), ('admin_staff', 'Administrative Staff')], max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.IntegerField(choices=[('Playgroup', 'Playgroup'), (-2, 'PP1'), (-1, 'PP2'), (1, 'G1'), (2, 'G2'), ('3', 'G3'), ('4', 'G4'), ('5', 'G5'), ('6', 'G6'), ('General_teacher', 'General Teacher'), ('support_staff', 'Support Staff'), ('admin_staff', 'Administrative Staff')]),
        ),
    ]
