# Generated by Django 3.2.4 on 2021-10-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_auto_20211029_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='grade',
            field=models.CharField(choices=[('Playgroup', -3), ('PP1', -2), ('PP2', -1), ('G1', 1), ('G2', 2), ('G3', 3), ('G4', 4), ('G5', 5), ('G6', 6), ('General Teacher', 7), ('Support Staff', 8), ('Administrative Staff', 9)], max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.IntegerField(choices=[('Playgroup', -3), ('PP1', -2), ('PP2', -1), ('G1', 1), ('G2', 2), ('G3', 3), ('G4', 4), ('G5', 5), ('G6', 6), ('General Teacher', 7), ('Support Staff', 8), ('Administrative Staff', 9)]),
        ),
    ]
