# Generated by Django 3.2.4 on 2021-10-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_auto_20211029_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='grade',
            field=models.IntegerField(choices=[(-3, 'Playgroup'), (-2, 'PP1'), (-1, 'PP2'), (1, 'G1'), (2, 'G2'), (3, 'G3'), (4, 'G4'), (5, 'G5'), (6, 'G6'), (7, 'General Teacher'), (8, 'Support Staff'), (9, 'Administrative Staff')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.IntegerField(choices=[(-3, 'Playgroup'), (-2, 'PP1'), (-1, 'PP2'), (1, 'G1'), (2, 'G2'), (3, 'G3'), (4, 'G4'), (5, 'G5'), (6, 'G6'), (7, 'General Teacher'), (8, 'Support Staff'), (9, 'Administrative Staff')]),
        ),
    ]
