# Generated by Django 3.2.4 on 2021-10-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_auto_20211029_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='transfered',
            field=models.BooleanField(default=True, verbose_name='Transfered or not'),
        ),
        migrations.AddField(
            model_name='student',
            name='transfered',
            field=models.BooleanField(default=True, verbose_name='Transfered or not'),
        ),
    ]
