# Generated by Django 3.2.4 on 2021-10-31 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_alter_staff_transfered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='transfered',
            field=models.BooleanField(default=False, verbose_name='Transfered?'),
        ),
        migrations.AlterField(
            model_name='student',
            name='transfered',
            field=models.BooleanField(default=True, verbose_name='Transfered?'),
        ),
    ]
