# Generated by Django 3.2.4 on 2021-10-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_auto_20211031_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='transfered',
            field=models.BooleanField(default=False, verbose_name='Transfered?'),
        ),
    ]
