# Generated by Django 3.2.4 on 2021-10-31 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.staff'),
        ),
    ]
