# Generated by Django 3.2.4 on 2021-11-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0047_remove_staff_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='photo',
            field=models.ImageField(default='john.png', upload_to='profile_photos'),
        ),
    ]
