# Generated by Django 2.1.15 on 2021-12-21 19:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(choices=[('Cash_at_hand', 'Cash with Teacher'), ('Cash_at_hand', 'Cash with Treasurer')], max_length=200)),
                ('account_number', models.IntegerField(null=True, unique=True)),
                ('opening_balance', models.IntegerField(null=True)),
                ('balance', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expender', models.CharField(max_length=200)),
                ('expense_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expense_amount', models.IntegerField()),
                ('spent_on', models.CharField(max_length=200)),
                ('receipt_number', models.IntegerField(null=True, unique=True)),
                ('receipt_photo', models.ImageField(upload_to='receipts')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('Term 1', 'Term 1'), ('Term 2', 'Term 2'), ('Term 3', 'Term 3')], max_length=100)),
                ('termly_fee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_by', models.CharField(max_length=200)),
                ('payable_towards', models.CharField(choices=[('development_fee', 'Development Fee'), ('motivation_fee', 'Motivation Fee'), ('exam_fee', 'Exam Fee'), ('tuition_fee', 'Tuition Fee')], default='tuition_fee', max_length=200)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount_paid', models.IntegerField(null=True)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('mpesa', 'Mpesa')], default='Cash', max_length=200)),
                ('receipt_number', models.IntegerField(null=True, unique=True)),
                ('acc_balance', models.IntegerField(default=0)),
                ('personal_balance', models.IntegerField(default=0)),
                ('payment_status', models.CharField(default='Underpaid', max_length=200)),
                ('total_pay', models.IntegerField(default=0)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_received_by', to='blog.Staff')),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.Fee')),
            ],
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=200)),
                ('transaction_amount', models.IntegerField(null=True)),
                ('transaction_by', models.CharField(max_length=200)),
                ('transaction_date', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.Account')),
            ],
        ),
    ]
