# Generated by Django 3.2.4 on 2021-10-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount_paid',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
