# Generated by Django 3.2.4 on 2021-10-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_auto_20211029_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='personal_balance',
            field=models.IntegerField(default=0),
        ),
    ]
