# Generated by Django 3.2.4 on 2021-11-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_alter_payment_personal_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='total_pay',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
